### ISSUE TITLE
 No module named 'simpleflow'

### ISSUE THREAD

**Issue by debin168** [PytLab/simpleflow#1]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-3dac5798c0f6> in <module>()
----> 1 import simpleflow as sf

ModuleNotFoundError: No module named 'simpleflow'
what's problem with my code?

**Comment by PytLab** [comment]
You should add the path including `simpleflow` to `PYTHONPATH` to make python be able to find the package.

**Comment by debin168** [comment]
thank u for u help ,it's working
